### ISSUE TITLE
Using  a controller to show tooltip

### ISSUE THREAD

**Issue by yohom** [escamoteur/super_tooltip#1]
Control the display of tooltip through controller instead of calling the `show` method directly on the `Tooltip` instance.

**Comment by escamoteur** [comment]
You mean because you could access the controller more easily?

**Comment by yohom** [comment]
Because I want to keep the `build` method more readable and minimize indirect widget references.😄
For example, in my opinion, something like this
```dart
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SuperTooltip(
		  controller: _someController, // the controller is responsable for showing the tooltip
          content: Text('test'),
        ),
      ),
    );
  }
```
is more readable than this 
```dart
  @override
  Widget build(BuildContext context) {
    final tooltip = SuperTooltip(content: Text('test')); // The tooltip instance itself is responsible for displaying the tooltip
	return MaterialApp(
      home: Scaffold(
        body: tooltip,
      ),
    );
  }
```

**Comment by escamoteur** [comment]
That makes totally sense. Would you like to make a PR?

**Comment by yohom** [comment]
ok, i will try it.

**Comment by jmolins** [comment]
Hi Thomas,
I'm chasing PRs and saw this one.
I began to code it but soon realized that it is not possible to do it as @yohom proposes.
Since the SuperTooltip is an overlay it can't be placed in the widget tree during building so it must forcibly be created on the fly when needed, as you do for a `PageRoute` or an `AlertDialog`.
Cheers
